Open-EO/openeo-python-client

- openeo/imagecollection.py
- openeo/rest/imagery.py
Added classes mean_time and median_time for RestImagery class. These processes are already defined for GEE backend.
> added the methods mean_time and median_time for RestImagery class

- openeo/rest/imagecollectionclient.py
- openeo/rest/imagery.py
- openeo/util.py
- tests/test_imagery.py
- tests/test_rastercube.py
- tests/test_util.py
> Accept value 0 for north/south/east/west in bbox_filter

- Jenkinsfile
- openeo/__init__.py
- openeo/error_summary.py
- setup.py
> Issue #60: rename (dist) package to "openeo" (instead of "openeo-api")

- examples/mundialis_example.py
- derived from examples/vito_example.py
> initial version of a mundialis backend example

- openeo/rest/conversions.py
- tests/rest/test_conversions.py
Initial helper to convert a timeseries JSON structure to pandas DataFrame
> Add helper to convert `aggregate_polygon` timeseries data to pandas DataFrame

- openeo/rest/connection.py
- openeo/rest/datacube.py
- openeo/rest/imagecollectionclient.py
- openeo/rest/job.py
- tests/data/0.4.0/aggregate_zonal_path.json
- tests/data/0.4.0/aggregate_zonal_polygon.json
- tests/data/1.0.0/aggregate_zonal_path.json
- tests/data/1.0.0/aggregate_zonal_polygon.json
- tests/rest/datacube/test_datacube100.py
- tests/rest/test_connection.py
- tests/rest/test_job.py
Fixes #129 
will conflict with #128
> improve 1.0-style process graph submit requests

- docs/basics.rst
- docs/udf.rst
- openeo/__init__.py
- openeo/rest/datacube.py
- openeo/rest/processbuilder.py
- tests/data/1.0.0/apply_absolute.json
- tests/rest/datacube/test_datacube100.py
- tests/rest/datacube/test_processbuilder.py
This PR is about how we specify callbacks in the Python client. Untill now, we had:
- support for specific cases, like band math
- direct calls for process + callback, like reduce_temporal_udf, apply_dimension
- some use of internal API (PGNode) where users required some knowledge of openeo process specs
So basically not a generic solution that works in all cases.
This PR adds a processbuilder, which is similar to an ImageCollection/DataCube so you build a process graph by calling methods on it.
The difficult bit is how to link the result into the parent graph, with as little hassle as possible. This is context specific, as different processes use different parameter names etcetera.
Both of these solutions have been implemented, question is which one we prefer and want to push in our …
> EP-3521 propose 2 new ways of specifying callbacks

- examples/mundialis_example.py
- examples/mundialis_extended.py
- examples/mundialis_mini.py
Note: mundialis_extended.py cloned from py3_process_wrapper-wcps_eurac.py with THANKS.
> WIP: updated Python scripts for openEO actinia/GRASS GIS backend

- CHANGELOG.md
- openeo/rest/connection.py
- openeo/rest/datacube.py
- openeo/rest/imagecollectionclient.py
- tests/data/batch_job.json
- tests/rest/test_job.py
- tests/test_batch_jobs.py
> support title/description/...  in DataCube.send_job (and don't send None values)

- docs/processes.rst
- grammatical error
- I think this was meant in the my_bandmath function, but I could be wrong
Don't know if master is correct to merge to, let me know.
> small corrections

- CHANGELOG.md
- openeo/rest/auth/oidc.py
- openeo/rest/connection.py
- tests/rest/auth/test_oidc.py
- tests/rest/test_connection.py
> add support for OIDC device auth grant without PKCE or secret

- CHANGELOG.md
- openeo/rest/datacube.py
- tests/rest/datacube/test_datacube100.py
fixes #229 
related to  openEOPlatform/documentation#10
> add proper child callback support for fit_curve and predict_curve

- CHANGELOG.md
- openeo/internal/processes/generator.py
- openeo/processes.py
- tests/rest/datacube/test_processbuilder.py
Fixes #228
related to  openEOPlatform/documentation#10
> Add ProcessBuilder `array_element(data, n)` through `data[n]` syntax

- CHANGELOG.md
- docs/processes.rst
- openeo/rest/connection.py
- tests/rest/test_connection.py
> Add describe_process #269

- openeo/rest/mlmodel.py
removing "format" from `save_ml_model`
> Issue #279 save_ml_model has no format parameter

- CHANGELOG.md
- openeo/rest/auth/auth.py
- openeo/rest/connection.py
- openeo/util.py
- tests/rest/auth/test_oidc.py
- tests/rest/test_connection.py
> Issue #298: try to refresh access token when expired

- CHANGELOG.md
- docs/auth.rst
- openeo/rest/auth/oidc.py
- openeo/rest/auth/testing.py
- tests/rest/auth/test_oidc.py
Implements issue https://github.com/Open-EO/openeo-python-client/issues/335 and replaces PR https://github.com/Open-EO/openeo-python-client/pull/360
> Issue335 (continued) OIDC support verification_uri_complete

- CHANGELOG.md
- openeo/extra/job_management.py
- setup.py
- tests/extra/test_job_management.py
Implements issue https://github.com/Open-EO/openeo-python-client/issues/365
> Issue #365 Add resilience to job manager

- .github/workflows/unittests.yml
- openeo/config.py
- tests/rest/test_userfile.py
> unittests GH workflow: add a windows run

- CHANGELOG.md
- openeo/internal/jupyter.py
- openeo/rest/auth/oidc.py
- openeo/rest/auth/testing.py
- openeo/util.py
- tests/rest/auth/test_cli.py
- tests/rest/auth/test_oidc.py
- tests/rest/conftest.py
- tests/rest/test_connection.py
- tests/test_util.py
draft PR for self review (issue #237)
> Issue #237 Progress bar while waiting for OIDC device code

- CHANGELOG.md
- openeo/rest/connection.py
- tests/rest/test_connection.py
> client cred support in authenticate_oidc

- CHANGELOG.md
- openeo/udf/run_code.py
- tests/udf/test_run_code.py
- tests/udf/udf_code/ndvi03.py
> #310 allow udf's that work directly on DataArray

- openeo/local/connection.py
Related to issue https://github.com/Open-EO/openeo-python-client/issues/538
> added auto_decode argument to local.connection.execute

- CHANGELOG.md
- openeo/api/process.py
- tests/api/test_process.py
convenience method for udp parameter that is compatible with load_collection spatial_extent
> add spatial_extent helper

- CHANGELOG.md
- openeo/rest/datacube.py
- tests/rest/datacube/test_datacube100.py
Draft PR for #592
Not to merge quickly, best is to wait for https://github.com/Open-EO/openeo-python-driver/commit/15b72a7764e11ac1e85c52681e0cdf7eac4697c5 being propagated in all the necessary deployments
> `apply_polygon()`: rename `polygons` argument to `geometries`

- CHANGELOG.md
- openeo/rest/datacube.py
- tests/rest/datacube/test_datacube.py
> Disallow ambiguous single string argument in filter_temporal #628

- openeo/rest/connection.py
> issue #689 create directory in connection.download if it doesn't exist

- openeo/udf/run_code.py
- tests/udf/test_run_code.py
- tests/udf/udf_code/multiply_factor.py
https://github.com/Open-EO/openeo-python-client/issues/556
> Execute local udf context

- CHANGELOG.md
- docs/api.rst
- docs/federation-extension.rst
- docs/index.rst
- openeo/api/logs.py
- openeo/rest/auth/testing.py
- openeo/rest/capabilities.py
- openeo/rest/connection.py
- openeo/rest/job.py
- openeo/rest/models/federation_extension.py
- openeo/rest/models/general.py
- openeo/rest/models/logs.py
- openeo/rest/service.py
- tests/internal/test_jupyter.py
- tests/rest/auth/test_testing.py
- tests/rest/conftest.py
- tests/rest/models/test_federation_extension.py
- tests/rest/models/test_general.py
- tests/rest/models/test_logs.py
- tests/rest/test_capabilities.py
- tests/rest/test_connection.py
- tests/rest/test_job.py
> Add support for federation extension

- openeo/internal/documentation.py
- openeo/rest/connection.py
- openeo/rest/datacube.py
- openeo/rest/job.py
- openeo/rest/mlmodel.py
- openeo/rest/result.py
- openeo/rest/stac_resource.py
- openeo/rest/vectorcube.py
- tests/conftest.py
- tests/internal/test_documentation.py
> Issue720 synchronize docs
