Open-EO/openeo-python-client

openeo/rest/rest_connection.py

Feel free to reject this PR if this change is not suitable for API versions after 0.3.1.
- Previously, several parameters were not used
- adds output_format, output_parameters, title, description, plan, budget
- relates to #45

feat(create_job): parameters are now used

---

openeo/graphbuilder.py
openeo/rest/imagecollectionclient.py
tests/test_graphbuilder.py

quickfix for issue #50
Explicitly sort source graph items in merge functionality of GraphBuilder to minimize node key ("from_node") renaming

Issue #50 correctly handle process renaming when merging two graph builders in ImageCollectionClient._reducte_bands_binary

---

openeo/rest/imagecollectionclient.py
tests/aggregate_zonal.json
tests/apply_dimension_temporal_cumsum.json
tests/evi_graph.json
tests/notequal.json
tests/test_bandmath.py
tests/test_logical_operators.py
tests/test_temporal_ops.py
tests/test_zonal_stats.py
tests/udf_graph.json

- use "load_collection" instead of "get_collection" for API version >= 0.4.0
- in unit tests: just use `assert a == b` instead of `print(json.dumps(...)); self.assertDictEqual(...)` as pytest  already gives actionable difference information by default

use `load_collection` instead of `get_connection` for API version 0.4.0 and above

---

openeo/capabilities.py
openeo/rest/imagecollectionclient.py
openeo/rest/rest_capabilities.py
openeo/rest/rest_connection.py
tests/test_capabilities.py
tests/test_rest_session.py

Two things in this PR:
- add "api_version" to Capabilities and deprecating "version" field (following 0.4.0 API)
- make the API version checking more generic for future usage (not only 0.4.0)

Add "api_version" to Capabilties and make (API) version checking more generic

---

openeo/rest/imagecollectionclient.py
openeo/rest/rest_connection.py
tests/logical_and.json
tests/logical_or.json
tests/test_logical_operators.py

as discussed with @jdries : this commit adds support for numpy/pandas style and/or logical operations, e.g.
mask = (data == 2) | (data == 5)

Band math: add support for logical and/or operations

---

openeo/rest/imagecollectionclient.py

merging #54  together with  #55  caused a `NameError: name 'LooseVersion' is not defined` issue

fixup! Merge pull request #54 from soxofaan/load_collection

---

openeo/internal/process_graph_visitor.py
tests/test_GraphVisitor.py

`ProcessGraphVisitor._list_to_graph`:
- simplify logic
- Improve docblock and function name (deprecate old name)
- move related tests from openeo-python-driver

Simplify `ProcessGraphVisitor._list_to_graph` and rename to `dereference_from_node_arguments`

---

openeo/__init__.py

client version has nothing to do with openEO API version
this PR avoids the confusion (see #65 )

Issue #65: openeo.client_version() returns client version

---

examples/eodc_example.py
examples/notebooks/Compositing.ipynb
examples/notebooks/PoC_EODC.ipynb
examples/notebooks/PoC_EURAC.ipynb
examples/notebooks/PoC_GEE_UsingProcess.ipynb
examples/phenology_example.py
openeo/imagecollection.py
openeo/process/process.py
openeo/rest/imagecollectionclient.py
openeo/rest/imagery.py
openeo/util.py
requirements.txt
tests/test_imagery.py
tests/test_rastercube.py
tests/test_util.py
tests/test_zonal_stats.py

Addresses #67: ImageCollection "API" 
- deprecate old style `date_range_filter`, `filter_daterange` and `bbox_filter`
- promote `filter_temporal` and `filter_bbox` instead (which are more in line with latest spec)
- support different call patterns for `filter_temporal` (no keyword args, with start_date/end_date, with extent)
- provide bit of backwards compatibility with old style subclasess (e.g. for in openeo-geopyspark-driver)

Better deprecation of old style date_range_filter and bbox_filter

---

openeo/rest/imagecollectionclient.py

This is proof of concept to export process graphs to Graphviz objects, which have `_repr_svg_()`, so render nicely in jupyter notebook (https://graphviz.readthedocs.io/en/stable/manual.html#jupyter-notebooks)
The implementation assumes presence of the graphviz python library (https://graphviz.readthedocs.io/en/stable/), which I would define as an optional dependency
usage example:

Request for comments: Export process graph to Graphviz for visualization

---

openeo/rest/imagecollectionclient.py

in the client the process stretch_colors was correctly deprecated in favor of linear_scale_range, but this one was not present.

Adds process linear_scale_range

---

.travis.yml
README.md
requirements-dev.txt
requirements.txt
setup.py

fixes #74 :
- drop requirement.txt files
- just define deps in setup.py
- simplifies installation procedure

Drop requirements.txt in favor of standard dependency declaration in setup.py

---

openeo/rest/auth/oidc.py
openeo/rest/connection.py
tests/rest/auth/test_oidc.py

based on request of @bgoesswe to allow specifying the port for the OAuth redirect in the OIDC PKCE flow
e.g. like this:
```
con.authenticate_OIDC("openeo-public", timeout=3, server_address=('', 1234))
```

Allow specifying OAuth redirect port (and host)

---

openeo/rest/datacube.py
openeo/rest/processbuilder.py
tests/rest/datacube/test_datacube100.py
tests/rest/datacube/test_processbuilder.py

follow-up of #149: we decided to pick method 1, method 2 is probably too confusing for Python users
removing method 2 again cleans up things quite a bit

EP-3521 remove second callback building method

---

CHANGELOG.md
openeo/rest/auth/cli.py
openeo/rest/auth/oidc.py
openeo/rest/connection.py
tests/rest/auth/test_cli.py
tests/rest/auth/test_oidc.py
tests/rest/test_connection.py

update Issue #192: Initial experimental implementation with a single default_client had to be adapted to multiple default clients from updated draft spec (Open-EO/openeo-api#366 was merged).
Not fully tested yet, I'm waiting for changes to VITO backend to be deployed

Issue #192: add support for default OIDC clients

---

CHANGELOG.md
openeo/rest/job.py
tests/rest/test_job.py

This implements issue [#352](https://github.com/Open-EO/openeo-python-client/issues/352)

Issue352 execute batch skip 502 bad gateway errors

---

.pre-commit-config.yaml

Now that the [darker](https://github.com/akaihola/darker) 1.6 has been released it might be a good time to update the pre-commit config file.
Previously we needed to pin [black ](https://github.com/psf/black) to an older version because of a bug : https://github.com/akaihola/darker/issues/403
With darker 1.6.1 that problem should be solved.

pre-commit config: Upgrade darker to version that avoids bug in black

---

CHANGELOG.md
openeo/rest/auth/config.py
tests/rest/auth/test_config.py

Fixes https://github.com/Open-EO/openeo-python-client/issues/387
Reinstated the old behavior of authenticate_oidc on Windows: 
When PrivateJsonFile may be readable by others, log message instead of raising a PermissionError.
There is a follow-up issue here #400, if we still want to find a more secure solution for Windows.
To be decided.
Also, for now I have left in the code that uses oschmod because:
1) when it does work, then it still adds a bit more security;
2) we would like to get a solution out quickly, but removing oschmod cleanly takes a bit more work and care.

Issue #387 openeo.connect, reinstate old behavior: no PermissionError on Windows

---

openeo/local/collections.py

Thanks to a recent version of rioxarray (>=0.13.0) including a PR that I started some time ago https://github.com/corteva/rioxarray/pull/592 we can have more detailed info from a geoTIFF into the STAC metadata: now if a band has the `description` field it gets translated into the band names instead of assigning just scalar values as band names.

[localprocessing] improved geotiff metadata

---

openeo/extra/job_management.py

Right now, the `on_job_done()` method will only be triggered when the cached state is `running` and the job status is `finished`. But it might be possible that the job manager was stopped and resumed later and jobs in another _active_ state (`created`, `queued`) finished in the mean time.
For example, this means that jobs going from `queued` to `finished` will not trigger the `on_job_done()` method.
This PR changes the behaviour of the job manager to trigger the `on_job_done()` method on the transition from **any** active state to the `finished` state.

Job manager: trigger on_job_done for finished job from all active states

---

openeo/local/connection.py

The `.parse_obj()` call can't handle `None` as temporal extent, avoid calling it if not necessary.
Avoid passing also other `None` parameters.
@soxofaan I would need to merge this before the next release, sorry for this last minute fix.
By the way, I will also think about some tests for the local processing functionality, to make sure I can catch this problems in advance.

FIx load_stac parameters

---

docs/udf.rst
openeo/udf/udf_signatures.py

Separating metadata transformation allows process graph analysis to work better when UDF's perform more complex transformations.
One example was requested in this issue:
https://github.com/Open-EO/openeo-geopyspark-driver/issues/412
Applies for instance to UDF's that:
- change band labels
- change spatial resolution
- change crs of spatial dimension
- change timestamps on temporal dimension
I requested some reviews as this is an extension of the UDF API. It's a non-breaking change, UDF's that work will continue to work.
@m-mohr  I'll want to make this an agenda topic on one of the next dev meetings. Do we require PSC approval for changes to UDF API?

define a new udf signature to separate metadata from data transformation

---

openeo/local/connection.py

@soxofaan @jdries
The introduction of the validate parameter here: https://github.com/Open-EO/openeo-python-client/blob/0fbe895da2a0cd5e499c773df5ffd8aef9a63b2b/openeo/rest/datacube.py#L2211 breaks all the local processing calls.
This PR fixes this, urgent to merge and release.

Urgent: add validate to local .execute()

---

CHANGELOG.md
openeo/rest/connection.py
openeo/rest/datacube.py
tests/rest/datacube/test_datacube.py

github issue #499
added try/except to connection.execute to catch json decode errors
If a json decode error occurs, the response is return raw. 
(Follows [eafp](https://docs.python.org/2/glossary.html#term-eafp))

catch json decode errors in connection.execute

---

CHANGELOG.md
openeo/rest/__init__.py
openeo/rest/connection.py
openeo/rest/job.py
openeo/rest/userfile.py

issue #528
this affects response.iter_content in the following functions:
- openeo.rest.connection.Connection.download
- openeo.rest.job.Job.download
- openeo.rest.userfile.UserFile.download
in Job.download the chunk size can still be overwritten by the user

changed default download chunk size to 10MB

---

openeo/internal/documentation.py

This improves static type checkers ability to infer typing.
Related to: #542

Use generic type definition in the openeo_process decorator

---

CHANGELOG.md
openeo/metadata.py
tests/test_metadata.py

Issue464 cube metadata

---

CHANGELOG.md
docs/cookbook/job_manager.rst
openeo/extra/job_management.py
tests/extra/test_job_management.py

Another step for issue #571 : allow user to specify a custom job database in run_jobs

Start supporting custom job databases in MultiBackendJobManager

---

CHANGELOG.md
openeo/extra/job_management.py
tests/extra/test_job_management.py

This proposal tries to support very large job databases in the job manager. It adjusts the job database interface to allow retrieving jobs with a specific status, and putting a limit on the maximum amount of jobs to return.

extend job database interface to allow more granular querying on status

---

openeo/extra/job_management.py

openEO on cdse also throws 500, job manager should not immediately give up, but continue with retrying https://github.com/Open-EO/openeo-python-client/issues/624

add 500 to retry list

---

CHANGELOG.md
openeo/rest/connection.py
openeo/rest/datacube.py
tests/rest/datacube/test_datacube.py
tests/rest/test_connection.py

This allows to use `openeo.rest.datacube.DataCube.load_stac(...)`
This way, we can use the python client to generate process graphs without an openeo backend.

Connectionless load stac

---

openeo/internal/warnings.py
openeo/rest/job.py
tests/internal/test_warnings.py
tests/rest/datacube/test_datacube100.py

fix legacy alias warning

---

openeo/extra/job_management.py

index for processing started always at index=0. If running on different backend this submitted the same jobs but to different backends.

fix broken multibackend use

---

CHANGELOG.md
docs/api.rst
docs/datacube_construction.rst
openeo/__init__.py
openeo/internal/graph_building.py
openeo/rest/_testing.py
openeo/rest/connection.py
openeo/rest/datacube.py
openeo/rest/multiresult.py
openeo/rest/udp.py
tests/internal/test_graphbuilding.py
tests/rest/conftest.py
tests/rest/test_connection.py
tests/rest/test_multiresult.py

Add support for multiple result node

---

openeo/rest/job.py

https://github.com/Open-EO/openeo-geopyspark-driver/issues/877

Avoid making empty fail if _get_response failed. 

---

CHANGELOG.md
openeo/extra/job_management.py
openeo/rest/_testing.py
tests/extra/test_job_management.py
tests/rest/test_testing.py

self-review PR for #656 (and related test fine-tuning)

avoid dtype loading mistakes in `CsvJobDatabase` on empty columns

---

CHANGELOG.md
openeo/extra/job_management.py
openeo/rest/_testing.py
tests/extra/test_job_management.py

added costs as a column to tracking databases

---

CHANGELOG.md
openeo/metadata.py
openeo/rest/datacube.py
openeo/util.py
setup.py
tests/rest/test_connection.py
tests/test_metadata.py
tests/test_util.py

Fixes #666
load_stac: fallback on "extent" based temporal dimension when "cube:dimension" is not present in metadata

fallback temporal dim when no cube:dimension in STAC metadata

---

CHANGELOG.md
openeo/rest/connection.py
tests/rest/test_job.py

instead of fake "unlimited" which was capped in practice anyway
ref: #677

Change `list_jobs()` limit to 100

---

CHANGELOG.md
docs/conf.py
openeo/extra/job_management/__init__.py
openeo/rest/_connection.py
openeo/rest/_testing.py
openeo/rest/connection.py
openeo/rest/job.py
openeo/utils/http.py
setup.py
tests/rest/test_job.py
tests/utils/test_http.py

Automatically retry on 429 Too Many Requests

---

openeo/extra/artifacts/_s3sts/sts.py
tests/extra/artifacts/_s3sts/test_s3sts.py

If a token is expired we can refresh it by doing another OpenEO interaction. By allowing 3 attempts for the STS service and by doing a very wide except clause we also make ourselves more robust against intermittent errors.

feature: handle expired token gracefully for artifact helper
